*Migrate scripts over to Python 3. Tested on local Python 3.10 - successful build, app working properly. *Provide support for OpenRC: service script in /etc/init.d + edit debian_package scripts to check for systemd/openrc and execute command accordingly. *Add content map for README.md *Ignore IDE stuff in .gitignore

diff --git a/installer/linux/additional_files/postinst_rpm b/installer/linux/additional_files/postinst_rpm
--- a/installer/linux/additional_files/postinst_rpm
+++ b/installer/linux/additional_files/postinst_rpm
@@ -2,8 +2,21 @@
 # This file overwrites the debian-specific postinst during fpm call in build script 
 # So if multi-platform change is needed remember to change that file as well
 set -e
+
+# Determine is system uses systemd as init system
+if [ -d "/run/systemd/system" ]
+then
 systemctl enable windscribe-helper
 systemctl start windscribe-helper
+elif [ -d "/run/openrc" ]
+then
+rc-update add windscribe-helper default
+rc-service windscribe-helper start
+else
+echo "Unable to determine init system"
+exit 1
+fi
+
 ln -s /usr/local/windscribe/windscribe-cli /usr/local/bin/windscribe-cli
 
 echo linux_rpm_x64 > ../etc/windscribe/platform # platform-specific
diff --git a/installer/linux/debian_package/DEBIAN/preinst b/installer/linux/debian_package/DEBIAN/preinst
--- a/installer/linux/debian_package/DEBIAN/preinst
+++ b/installer/linux/debian_package/DEBIAN/preinst
@@ -4,27 +4,46 @@ end=$((SECONDS+10))
 
 while :
 do
-  if [ -z "$(ps -eo args | grep WindscribeEngine | grep -v grep)" ]; then
+  if [ -z "$(ps -eo args | grep WindscribeEngine | grep -v grep)" ]
+  then
     break
   fi
   
-  if [ $SECONDS -gt $end ]; then
+  if [ $SECONDS -gt $end ]
+  then
     echo 'Error during Windscribe installation. WindscribeEngine is running. Please re-launch Windscribe. And try to update again.'
     exit 1
   fi
 done
 
+# Determine is system uses systemd as init system
+if [ -d "/run/systemd/system" ]
+then
 systemctl stop windscribe-helper > /dev/null 2>&1
 systemctl disable windscribe-helper > /dev/null 2>&1
+elif [ -d "/run/openrc" ]
+then
+rc-service windscribe-helper stop > /dev/null 2>&1
+rc-update del windscribe-helper > /dev/null 2>&1
+else
+echo "Unable to determine init system"
+exit 1
+fi
 
 # Stop and disable firewalld service if it is active, otherwise it will conflict with iptables on OS reboot
 # Relevant for Fedora distributions
-systemctl is-active --quiet firewalld
-if [ $? -eq 0 ] 
+if [ -f "/usr/sbin/firewalld" ]
 then
-   echo "Firewalld service is running. It will be stopped and disabled to avoid conflicts with the Windscribe iptables firewall."
-   sudo systemctl stop firewalld
-   sudo systemctl disable firewalld
+  echo "Firewalld service is installed. It will be stopped and disabled to avoid conflicts with the Windscribe iptables firewall."
+  if [ -d "/run/systemd/system" ]
+  then
+    systemctl stop firewalld > /dev/null 2>&1
+    systemctl disable firewalld > /dev/null 2>&1
+  elif [ -d "/run/openrc" ]
+  then
+    rc-service firewalld stop > /dev/null 2>&1
+    rc-update del firewalld > /dev/null 2>&1
+  fi
 fi
 
 echo "Finish pre-install script"
