v2.10.4

diff --git a/installer/linux/debian_package/DEBIAN/preinst b/installer/linux/debian_package/DEBIAN/preinst
--- a/installer/linux/debian_package/DEBIAN/preinst
+++ b/installer/linux/debian_package/DEBIAN/preinst
@@ -4,14 +4,14 @@ end=$((SECONDS+10))
 
 while :
 do
-  if [ -z "$(ps -eo args | grep WindscribeEngine | grep -v grep)" ]; then
-    break
-  fi
+    if [ -z "$(ps -eo args | grep WindscribeEngine | grep -v grep)" ]; then
+        break
+    fi
 
-  if [ $SECONDS -gt $end ]; then
-    echo 'Error during Windscribe installation. WindscribeEngine is running. Please re-launch Windscribe. And try to update again.'
-    exit 1
-  fi
+    if [ $SECONDS -gt $end ]; then
+        echo 'Error during Windscribe installation. WindscribeEngine is running. Please re-launch Windscribe. And try to update again.'
+        exit 1
+    fi
 done
 
 systemctl stop windscribe-helper > /dev/null 2>&1 || true
@@ -22,9 +22,9 @@ systemctl disable windscribe-helper > /dev/null 2>&1 || true
 systemctl is-active --quiet firewalld
 if [ $? -eq 0 ]
 then
-   echo "Firewalld service is running. It will be stopped and disabled to avoid conflicts with the Windscribe iptables firewall."
-   sudo systemctl stop firewalld
-   sudo systemctl disable firewalld
+    echo "Firewalld service is running. It will be stopped and disabled to avoid conflicts with the Windscribe iptables firewall."
+    sudo systemctl stop firewalld
+    sudo systemctl disable firewalld
 fi
 
 echo "Finish pre-install script"
